<div class="wrap" id="origin-page">
	<script type="text/javascript" id="origin-preview-function">
		<?php print $css_js_function ?>
	</script>
	
	<form method="post" action="" enctype="multipart/form-data" id="origin">
		<div id="origin-buttons">
			<div class="preview">
				<button data-href="<?php print $start_url ?>"><?php _e('Preview', 'origin') ?></button>
			</div>
			
			<div class="save">
				<input type="submit" value="<?php _e('Save Changes','origin') ?>" />
			</div>
		</div>
		
		<div id="icon-themes" class="icon32"><br></div>
		<h2><?php _e('Site Design', 'origin') ?></h2>
		
		<?php if($updated) : ?>
			<div id="settings_updated" class="updated settings-error">
				<p>
					<?php _e('Design settings <strong>saved</strong>.', 'origin') ?>
					<?php if(!empty($_GET['ref'])) printf(__('Go back to %s', 'origin'), '<a href="'.esc_attr($_GET['ref']).'">'.strip_tags($_GET['ref']).'</a>. ') ?>
				</p>
			</div>
		<?php endif; ?>
		
		<div id="filters">
			<div class="filter">
				<h3><?php _e('Section', 'origin') ?></h3>
				<select id="section-filter" name="filter_section" data-placeholder="<?php _e('Filter By Section', 'origin') ?>">
					<option value=""></option>
					<?php foreach($this->settings->get_settings() as $section_id => $section) : ?>
						<option value="<?php print $section_id ?>" <?php selected($user_filters['section'], $section_id) ?>><?php print $section['title'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
			
			<div class="filter">
				<h3><?php _e('Tags', 'origin') ?></h3>
				
				<?php
					$all_tags = array();
					foreach($this->settings->get_settings() as $section_id => $section){
						foreach($section['settings'] as $field_id => $field){
							if(isset($field['tags'])) foreach($field['tags'] as $tag){
								$all_tags[] = $tag;
							}
						}
					}
					
					array_map('strtolower', $all_tags);
					$all_tags = array_unique($all_tags);
					sort($all_tags);
				?>
				
				<select id="tag-filter" name="filter_tag" data-placeholder="<?php _e('Filter By Tag', 'origin') ?>">
					<option value=""></option>
					<?php foreach($all_tags as $tag) : ?>
						<option value="<?php print $tag ?>" <?php selected($user_filters['tag'], $tag) ?>><?php print $tag ?></option>
					<?php endforeach ?>
				</select>
			</div>
			
			<div class="filter">
				<h3><?php _e('Selectors', 'origin') ?></h3>
				
				<?php
					$all_selectors = array_unique($all_selectors);
					sort($all_selectors);
				?>
				
				<select id="selector-filter" name="filter_selector" <?php if(!empty($user_filters['selector'])) print 'value="'.esc_attr($user_filters['selector']).'"'; ?> data-placeholder="<?php _e('Filter By CSS Selector', 'origin') ?>">
					<option value=""></option>
					<?php foreach($all_selectors as $selector) : ?>
						<option value="<?php esc_attr_e($selector) ?>" <?php selected($user_filters['selector'], $selector) ?>><?php esc_attr_e($selector) ?></option>
					<?php endforeach; ?>
				</select>
			</div>
			
			<div class="clear"></div>
			
		</div>
		
		<table class="form-table"><tbody>
			<?php foreach($this->settings->get_settings() as $section_id => $section) : ?>
				<?php foreach($section['settings'] as $field_id => $field) : $obj = $this->settings->get_object($section_id, $field_id); ?>
					<?php
						$styles = array();
						if(!empty($class->error)) $styles[] = 'background-color:#ffecec';
					?>
					<tr valign="top" <?php if(!empty($styles)) { print 'style="'.esc_attr(implode(';', $styles)).'"'; } ?>>
					<th scope="row">
						<?php print $field['label'] ?>
						<?php if(!empty($class->error)) : ?><div class="description" style="color:red"><?php print $class->error ?></div><?php endif ?>
						<div class="info"><?php print $section['title'] ?></div>
					</th>
					<td>
					<fieldset class="origin type-<?php print $field['type'] ?>"
						data-section="<?php esc_attr_e($section_id) ?>"
						data-selectors="<?php if(!empty($selectors[$section_id][$field_id])) esc_attr_e(implode(' , ', $selectors[$section_id][$field_id])) ?>"
						data-tags="<?php if(!empty($field['tags'])) esc_attr_e(implode(' , ', $field['tags'])) ?>"
						>
						
						<legend class="screen-reader-text"><span><?php print $field['#label'] ?></span></legend>
						
						<?php $obj->render_form(); ?>
						<?php if(!empty($field['description'])) : ?><p class="description"><?php print $field['description'] ?></p><?php endif; ?>
					</fieldset>
					</td>
					</tr>
				<?php endforeach ?>
			<?php endforeach ?>
		</tbody></table>
		
		<input type="hidden" name="action" value="save" />
	</form>
	
	<?php if(($score = get_option('origin_'.$this->theme_name.'_score', false)) !== false) : ?>
		<p class="origin-score">
			<?php _e('Your design score is:', 'origin'); ?>
			<score><?php print round($score*100,2) ?></score>
		</p>
	<?php endif; ?>
	
	<!--[if lte IE 8]>
		<!-- Chrome frame for legacy IE -->
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js"></script>
		<script>
			CFInstall.check({
				mode: "overlay",
				destination: "<?php print home_url() ?>/wp-admin/themes.php?page=origin"
			});
		</script>
	<![endif]-->
</div>